### ISSUE TITLE
Not working some routes (example: pagination) for View table

### ISSUE THREAD

**Issue by heySasha** [nestjsx/crud#202]
For query ```http://localhost:3000/?page=1&limit=3```
```
[Nest] 14748   - 08/05/2019, 4:05 PM   [ExceptionsHandler] syntax error at or near ")"
+5240ms

QueryFailedError: syntax error at or near ")"
    at new QueryFailedError (/Users/alex/Work/nest-cats/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/alex/Work/nest-cats/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/alex/Work/nest-cats/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/alex/Work/nest-cats/node_modules/pg/lib/client.js:211:17)
    at Connection.emit (events.js:200:13)
    at Connection.EventEmitter.emit (domain.js:471:20)
    at Socket.<anonymous> (/Users/alex/Work/nest-cats/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
```
I created repo for [example](https://github.com/heySasha/nest-cats).

**Comment by heySasha** [comment]
I fixed it. I added directive @PrimaryColumn.
```
export class OwnerView {
  @ViewColumn()
  @PrimaryColumn()  <---
  id: number;

  @ViewColumn()
  name: string;

  @ViewColumn()
  totalCats: number;
}
```
