### ISSUE TITLE
npm run serve is not working

### ISSUE THREAD

**Issue by Thananjeyan** [nestjsx/crud#29]
Step 5 of example app is failing error given below. am I missing any step.

```

E:\git_clones\NestJS\crud\integration\typeorm>npm run serve

> nestjsx-crud-typeorm@1.0.0 preserve E:\git_clones\NestJS\crud\integration\typeorm
> npm run db:sync -- -f=orm && npm run db:seeds -- -f=orm


> nestjsx-crud-typeorm@1.0.0 db:sync E:\git_clones\NestJS\crud\integration\typeorm
> ts-node -r tsconfig-paths/register node_modules/.bin/typeorm schema:sync "-f=orm"

E:\git_clones\NestJS\crud\integration\typeorm\node_modules\.bin\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at Object.<anonymous> (E:\git_clones\NestJS\crud\integration\typeorm\node_modules\ts-node\src\bin.ts:157:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nestjsx-crud-typeorm@1.0.0 db:sync: `ts-node -r tsconfig-paths/register node_modules/.bin/typeorm schema:sync "-f=orm"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nestjsx-crud-typeorm@1.0.0 db:sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TJ\AppData\Roaming\npm-cache\_logs\2019-02-01T07_35_46_818Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nestjsx-crud-typeorm@1.0.0 preserve: `npm run db:sync -- -f=orm && npm run db:seeds -- -f=orm`
npm ERR! Exit status 1
```

**Comment by Thananjeyan** [comment]
It is "typeorm": "^0.2.9"

**Comment by zMotivat0r** [comment]
Do you still have this issue?

**Comment by ap1969** [comment]
Hi, 
I've just cloned a fresh copy of the project. Did "npm install" then "npm run start:typeorm", and got the same issue as the original poster.

Andy

**Comment by zMotivat0r** [comment]
@ap1969 this project is a monorepo where yarn is used. These are the steps to run example project https://github.com/nestjsx/crud/wiki#example-projects

**Comment by ruslanguns** [comment]
@zMotivat0r I do have the same issue on `yarn start:typeorm` 

![image](https://user-images.githubusercontent.com/19806968/77424408-fb95b280-6dc8-11ea-9c25-134719ed92a0.png)

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.0
NPM Version    : 6.14.3

[Nest CLI]
Nest CLI Version : 7.0.2
```
