### ISSUE TITLE
TypeError: Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by joshnies-marketspark** [nestjsx/crud#342]
```json
"dependencies": {
    "@nestjs/common": "^6.10.9",
    "@nestjs/core": "^6.10.9",
    "@nestjs/platform-express": "^6.10.9",
    "@nestjs/typeorm": "^6.2.0",
    "@nestjsx/crud": "^4.2.0",
    "@nestjsx/crud-request": "^4.2.0",
    "@nestjsx/crud-typeorm": "^4.2.0"
},
"devDependencies": {
    "@nestjs/schematics": "^6.7.6",
    "@nestjs/testing": "^6.10.9"
}
```

Error occurs when not adding `query` property to `@Crud` decorator options and running tests for the controller.

Controller:
```ts
@Crud({
  model: {
    type: MyEntity
  }
})
@Controller('myentity')
export class MyEntityController {
  constructor(public service: MyEntityService) {}

  get base(): CrudController<MyEntity> {
    return this;
  }

  @Override()
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase!(req);
  }
}
```

Controller tests:
```ts
const crudParsed = new RequestQueryParser();
const crudReq: CrudRequest = {
  parsed: crudParsed.getParsed(),
  options: {}
};

describe('MyEntity Controller', () => {
  let controller: MyEntityController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        TypeOrmModule.forRoot(testOrmConfig),
        TypeOrmModule.forFeature([MyEntity])
      ],
      controllers: [MyEntityController],
      providers: [MyEntityService]
    }).compile();

    controller = module.get<MyEntityController>(MyEntityController);
  });

  describe('getMany', () => {
    it('should return many entities', async () => {
      const entities = await controller.getMany(crudReq);

      // ...
    });
  });
});
```

Error:
```
TypeError: Cannot read property 'exclude' of undefined

      57 |   getMany(@ParsedRequest() req: CrudRequest) {
    > 58 |     return this.base.getManyBase!(req);
         |                      ^
      59 |   }

      at MyEntityService.getAllowedColumns (../node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:447:31)
      at MyEntityService.getSelect (../node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:558:23)
      at MyEntityService.createBuilder (../node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:213:25)
      at MyEntityService.getMany (../node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:62:30)
      at MyEntityController.getManyBase (../node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:139:27)
      at MyEntityController.getMany (myentity/myentity.controller.ts:58:22)
      at Object.<anonymous> (myentity/myentity.controller.spec.ts:43:53)
```

### Fix:

Controller:
```ts
@Crud({
  model: {
    type: MyEntity
  },
  query: {}
})
@Controller('myentity')
export class MyEntityController {
  // ...
}
```

Controller tests:
```ts
const crudParsed = new RequestQueryParser();
const crudReq: CrudRequest = {
  parsed: crudParsed.getParsed(),
  options: {
    query: {}
  }
};

// ...
```

**Comment by zMotivat0r** [comment]
`crudOpts` - how do get it or compose?

**Comment by joshnies-marketspark** [comment]
> `crudOpts` - how do you get it or compose?

Sorry about that, updated.

**Comment by zMotivat0r** [comment]
you get an error because you miss an option composition. Here: https://github.com/nestjsx/crud/blob/d428123ace01a7aadf8f2089b7f0018df92a8d94/packages/crud/src/crud/crud-routes.factory.ts#L68-L106

**Comment by zMotivat0r** [comment]
so it's definitely not a bug
