### ISSUE TITLE
Main alias is not set 

### ISSUE THREAD

**Issue by Aibokalv** [nestjsx/crud#385]
there is a condition is that  i need use "filter" and  "join" operation;  my url path  is like this
http://localhost:7001/api/system/user/crud?join=dept&filter=dept.id||$in||1,2
in database  the dept.id field is a integer 
the stack info is like this
`
req:  { filter: 'dept.id||$in||11', join: 'dept' }
exception:  Error: Main alias is not set
    at SelectQueryBuilder.get [as alias] (D:\Mycode\newschool\src\query-builder\QueryBuilder.ts:114:19)
    at EntityManager.<anonymous> (D:\Mycode\newschool\src\entity-manager\EntityManager.ts:840:56)
    at step (D:\Mycode\newschool\node_modules\_tslib@1.10.0@tslib\tslib.js:136:27)
    at Object.next (D:\Mycode\newschool\node_modules\_tslib@1.10.0@tslib\tslib.js:117:57)
`

i don't if this problem is occur by typeorm  

the package.json is like this
`
    "@nestjsx/crud": "^4.4.1",
    "@nestjsx/crud-typeorm": "^4.4.1",
`

**Comment by zMotivat0r** [comment]
Could you please provide a repository with the minimal representation of this bug?
Thanks!

**Comment by zMotivat0r** [comment]
fixed in [v4.6.0](https://github.com/nestjsx/crud/releases/tag/v4.6.0)
