### ISSUE TITLE
Example project typeorm does not run out of the box

### ISSUE THREAD

**Issue by jessevanmuijden** [nestjsx/crud#420]
Executed the following commands
```
docker-compose up -d
yarn bootstrap
yarn db:prepare:typeorm
yarn start:typeorm
```

Result:
```
% yarn start:typeorm 
yarn run v1.19.2
$ npx nodemon -w ./integration/crud-typeorm -e ts node_modules/.bin/ts-node integration/crud-typeorm/main.ts
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): integration/crud-typeorm/**/*
[nodemon] starting `node node_modules/.bin/ts-node integration/crud-typeorm/main.ts`
Error: Cannot find module './crud/node_modules/@nestjsx/crud/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:306:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (./crud/integration/crud-typeorm/main.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Module.m._compile (./vng/crud/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
[nodemon] app crashed - waiting for file changes before starting...
```
Expected:
`The app is running on port 3000`

**Comment by zMotivat0r** [comment]
run `yarn build` once before `yarn start:typeorm`
