### ISSUE TITLE
500 error when getting entity list with relation using @Type decorator with discriminator and alwaysPaginate: true

### ISSUE THREAD

**Issue by noneedinmagic** [nestjsx/crud#463]
Hello! Have been debugging it for last two hours...

Getting TypeError (stack trace at the bottom). The problem is that classToPlain fails for the relation which uses @Type with dicsriminator (details here: https://github.com/typestack/class-transformer#providing-more-than-one-type-option)
The error is: `Cannot read property 'name' of undefined`. 
There problem is happening when I am using `alwaysPaginate: true`.
It happens that in `CrudResponseInterceptor`'s method `serialize` the contant `isArray` equals `false` cause the response object is not the plain array but `{ data: EntityClass[]; }`. So because of that condition which should check if an object is array and use .map method for transformation fails and tries to proccess whole data object as plain and convert it into class.

Stack trace:
```
[Nest] 23508   - 2020-04-07 17:16:52   [ExceptionsHandler] Cannot read property 'name' of undefined +420751ms
TypeError: Cannot read property 'name' of undefined
    at %project%\server\node_modules\class-transformer\TransformOperationExecutor.js:47:278
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.transform (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:30:19)
    at _loop_1 (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
    at %project%\server\node_modules\class-transformer\TransformOperationExecutor.js:53:41
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.transform (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:30:19)
    at _loop_1 (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (%project%\server\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
    at ClassTransformer.classToPlain (%project%\server\node_modules\class-transformer\ClassTransformer.js:9:25)
    at Object.classToPlain (%project%\server\node_modules\class-transformer\index.js:12:29)
    at CrudResponseInterceptor.transform (%project%\server\node_modules\@nestjsx\crud\lib\interceptors\crud-response.interceptor.js:38:35)
    at CrudResponseInterceptor.serialize (%project%\server\node_modules\@nestjsx\crud\lib\interceptors\crud-response.interceptor.js:49:28)
    at MapSubscriber.next.handle.pipe.operators_1.map [as project] (%project%\server\node_modules\@nestjsx\crud\lib\interceptors\crud-response.interceptor.js:27:66)
    at MapSubscriber._next (%project%\server\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (%project%\server\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (%project%\server\node_modules\rxjs\internal\operators\mergeMap.js:95:26)
    at InnerSubscriber._next (%project%\server\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (%project%\server\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (%project%\server\node_modules\rxjs\internal\operators\switchMap.js:89:26)
    at InnerSubscriber._next (%project%\server\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (%project%\server\node_modules\rxjs\internal\Subscriber.js:66:18)
    at %project%\server\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by noneedinmagic** [comment]
Any plans on looking into this?

**Comment by zMotivat0r** [comment]
I've couldn't reproduce this. Could you please generate a minimal repo with the reproduction of this issue?

**Comment by noneedinmagic** [comment]
> I've couldn't reproduce this. Could you please generate a minimal repo with the reproduction of this issue?

Got me a plenty of time, but here it is. https://github.com/noneedinmagic/nestjsx-crud-pagination-error

Just try getting `Person` with joined `roles` and you will get 500 error (result in DB should not be empty).

Also, u can disable `alwaysPaginate` and just set page param to 1, it also throws 500 error.

Swagger link: [http://localhost:8765/api/#/Person/getManyBasePersonControllerPerson](http://localhost:8765/api/#/Person/getManyBasePersonControllerPerson)

Also it would be nice if you might help with another issue about creating children entities without the need of setting up separate services and controllers. Maybe, I should create another issue and mention this one there?

Thanks.

**Comment by noneedinmagic** [comment]
@zMotivat0r did you look into this? Any suggestions?
