### ISSUE TITLE
Erro on start project: Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by eduscrakozabrus** [nestjsx/crud#475]
yarn run v1.22.4
$ npx nodemon -w ./integration/crud-typeorm -e ts node_modules/.bin/ts-node integration/crud-typeorm/main.ts
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): integration/crud-typeorm/**/*
[nodemon] starting `node node_modules/.bin/ts-node integration/crud-typeorm/main.ts`
Error: Cannot find module '/home/schekin/Projects/piomni-mc/crud/node_modules/@nestjsx/util/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/schekin/Projects/piomni-mc/crud/node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by zMotivat0r** [comment]
What's your OS and what was your previous steps to install the project?

**Comment by eduscrakozabrus** [comment]
> What's your OS and what were your previous steps to install the project?

ubuntu 18.04 
1. git clone ..
2. docker-compose up -d
3. yarn bootstrap
4. yarn db:prepare:typeorm
5. yarn start:typeorm - get this error

**Comment by zMotivat0r** [comment]
yep, my bad.
please do `yarn build` before `yarn start:typeorm`

**Comment by juliaguida** [comment]
node:internal/modules/cjs/loader:361 throw err; ^

Error: Cannot find module '/Users/node_modules/express/server.js'. Please verify that the package.json has a valid "main" entry

fixed the above error - by making sure the express.js was added into my package.json as a dependency.

"dependencies": { "ejs": "^3.1.6", "express-ejs": "^2.0.0", "express-ejs-layouts": "^2.5.1", "express.js": "^1.0.0" },
