### ISSUE TITLE
error: table name specified more than once

### ISSUE THREAD

**Issue by nmMmnmMmn** [nestjsx/crud#493]
## Environment
 - PostgreSQL 12.2
 - @nestjs/common@^7.0.7
 - @nestjsx/crud@^4.4.2
 - @nestjs/typeorm@^7.0.0
 - typeorm@^0.2.24

## Description
I have entities like:
```typescript
@Entity()
class AEntity {
  //...
  @OneToOne(/*...*/)
  test: TestEntity

  @OneToMany(/*...*/)
  b: BEntity[]
}

@Entity()
class BEntity {
  //...
  @ManyToMany(/*...*/)
  test: TestEntity[]
}
```
The controller of `AEntity`:
```typescript
@Crud({
  model: {
    type: AEntity,
  },
  query: {
    join: {
      test: {},
      b: {},
      'b.test': {}
   }
})
class AColtroller implements CrudController<AEntity> {
  // Bar
}
```
So when I try to get all these relations in one request
```
GET
http://localhost:3000/a?
    join=test
    &join=b
    &join=b.test
```
it would come up with query failure
```
error: table name "test" specified more than once
```
which in my real case, the error is:
```
query failed: SELECT DISTINCT "distinctAlias"."Album_id" as "ids_Album_id" FROM (SELECT "Album"."id" AS "Album_id", "belongsToArtists"."id" AS "belongsToArtists_id", "hasSongs"."id" AS "hasSongs_id", "belongsToArtists"."id" AS "belongsToArtists_id" FROM "public"."albums" "Album" LEFT JOIN "public"."artists_has_albums_albums" "belongsToArtists_Album" ON "belongsToArtists_Album"."albumsId"="Album"."id" LEFT JOIN "public"."artists" "belongsToArtists" ON "belongsToArtists"."id"="belongsToArtists_Album"."artistsId"  LEFT JOIN "public"."songs" "hasSongs" ON "hasSongs"."belongsToAlbumId"="Album"."id"  LEFT JOIN "public"."artists_has_songs_songs" "belongsToArtists_hasSongs" ON "belongsToArtists_hasSongs"."songsId"="hasSongs"."id" LEFT JOIN "public"."artists" "belongsToArtists" ON "belongsToArtists"."id"="belongsToArtists_hasSongs"."artistsId" WHERE (("Album"."id" = $1)) AND "Album"."deletedAt" IS NULL) "distinctAlias" ORDER BY "Album_id" ASC LIMIT 25 -- PARAMETERS: [1]
error: error: table name "belongsToArtists" specified more than once
    at Connection.parseE (/Users/username/dev/Project/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/Users/username/dev/Project/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/Users/username/dev/Project/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 130,
  severity: 'ERROR',
  code: '42712',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '423',
  routine: 'checkNameSpaceConflicts'
}
```

**Comment by zMotivat0r** [comment]
duplicate https://github.com/nestjsx/crud/issues/281
you need to read docs and use [aliases](https://github.com/nestjsx/crud/wiki/Controllers#join)

**Comment by nmMmnmMmn** [comment]
@zMotivat0r Thanks for reply!
Actually I did tried using `alias`
```typescript
    join: {
      belongsToArtists: {},
      hasSongs: {},
      'hasSongs.belongsToArtists': {
        alias: 'test',
      },
    },
```
but it seems didn't take any effect.
![图片](https://user-images.githubusercontent.com/21982381/80981550-b7cca900-8e5c-11ea-9519-e493737321ef.png)
it works if i use the original name. so I'm kinda confused right now. am I missing anything?
![图片](https://user-images.githubusercontent.com/21982381/80982092-683aad00-8e5d-11ea-9e69-5b9db46e1ee0.png)

**Comment by nmMmnmMmn** [comment]
> duplicate #281
> you need to read docs and use [aliases](https://github.com/nestjsx/crud/wiki/Controllers#join)

thank you for reply! i just figured it out. i was misunderstand to use alias in query. here's what i did. lmao
```
'b.test': {
  alias: 'foo'
}
================
GET
http://localhost:3000/a?
    join=test
    &join=b
    &join=foo  // which should be &join=b.test
```
