### ISSUE TITLE
WHERE clause table alias and column is unquoted--needed for postgresql

### ISSUE THREAD

**Issue by jeffreyschultz** [nestjsx/crud#502]
I am not sure if this is a @nestjsx/crud issue, if the issue is with TypeORM, or if its something I have done or not done.

The issue is in the WHERE clause: `FROM "document_section_comment" "DocumentSectionComment" WHERE (DocumentSectionComment.document_id = $1) -- PARAMETERS: [281]`

See how the table name and column are not quoted? This matters in postgresql, because if they are not quoted, they are lowercased, while if quoted, they are considered case sensitive. The `DocumentSectionComment` will be turned into a lower case `documentsectioncomment`, which will not match  up to the table alias.

```
import { Column, Entity, JoinColumn, ManyToOne, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { DocumentSection } from './document-section.entity';
import { User } from './user.entity';

@Entity('document_section_comment')
export class DocumentSectionComment {
  @PrimaryGeneratedColumn({ name: 'id' })
  id: number;

  @Column({ name: 'section_id' })
  sectionId: number;

  @Column({ name: 'content' })
  content: string;

  @Column({ name: 'created_dt' })
  createdDate: Date;

  @Column({ name: 'last_modified_dt' })
  lastModifiedDate: Date;

  @Column({ name: 'is_resolved' })
  isResolved: boolean;

  @Column({ name: 'parent_id' })
  parentId: number;

  @Column({ name: 'owner_id' })
  ownerId: number;

  @Column({ name: 'document_id' })
  documentId: number;

  @ManyToOne(() => DocumentSection)
  @JoinColumn({ name: 'section_id', referencedColumnName: 'id' })
  section: DocumentSection;

  @ManyToOne(() => DocumentSectionComment)
  @JoinColumn({ name: 'parent_id', referencedColumnName: 'id' })
  parent: DocumentSectionComment;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'owner_id', referencedColumnName: 'id' })
  owner: User;

  @OneToMany(
    () => DocumentSectionComment,
    $ => $.parent
  )
  @JoinColumn({ name: 'id', referencedColumnName: 'parent_id' })
  replies: DocumentSectionComment[];
}
```

```
import { CrudControllerBase } from '@app/core/controller';
import { DocumentSectionComment } from '@app/entities';
import { Controller, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { Crud } from '@nestjsx/crud';
import { JwtAuthGuard } from '../auth';
import { DocumentCommentService } from './document-comment.service';

@Crud({
  model: { type: DocumentSectionComment },
  params: {
    documentId: {
      field: 'document_id',
      type: 'number'
    },
    id: {
      field: 'id',
      type: 'number',
      primary: true
    }
  }
})
@UseGuards(JwtAuthGuard)
@ApiTags('forms')
@ApiBearerAuth()
@Controller('documents/:documentId/comments')
export class DocumentCommentController extends CrudControllerBase<DocumentSectionComment> {
  constructor(service: DocumentCommentService) {
    super(service);
  }
}
```

```
query failed: SELECT "DocumentSectionComment"."id" AS "DocumentSectionComment_id", "DocumentSectionComment"."section_id" AS "DocumentSectionComment_section_id", "DocumentSectionComment"."content" AS "DocumentSectionComment_content", "DocumentSectionComment"."created_dt" AS "DocumentSectionComment_created_dt", "DocumentSectionComment"."last_modified_dt" AS "DocumentSectionComment_last_modified_dt", "DocumentSectionComment"."is_resolved" AS "DocumentSectionComment_is_resolved", "DocumentSectionComment"."parent_id" AS "DocumentSectionComment_parent_id", "DocumentSectionComment"."owner_id" AS "DocumentSectionComment_owner_id", "DocumentSectionComment"."document_id" AS "DocumentSectionComment_document_id" FROM "document_section_comment" "DocumentSectionComment" WHERE (DocumentSectionComment.document_id = $1) -- PARAMETERS: [281]
error: error: missing FROM-clause entry for table "documentsectioncomment"
    at Connection.parseE (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 134,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '761',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3305',
  routine: 'errorMissingRTE'
}
[Nest] 19537   - 05/06/2020, 2:14:58 PM   [ExceptionsHandler] missing FROM-clause entry for table "documentsectioncomment" +740ms
QueryFailedError: missing FROM-clause entry for table "documentsectioncomment"
    at new QueryFailedError (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:310:20)
    at Socket.<anonymous> (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
```

**Comment by jeffreyschultz** [comment]
It's bizarre, because it works elsewhere, such as here: 

```
query: SELECT "FormField"."id" AS "FormField_id", "FormField"."name" AS "FormField_name", "FormField"."field" AS "FormField_field", "FormField"."form_id" AS "FormField_form_id" FROM "form_field" "FormField" WHERE ("FormField"."form_id" = $1) -- PARAMETERS: [1]
```

This makes me think its something with these particular set of classes.

**Comment by jeffreyschultz** [comment]
I figured out the issue. I put the column name in the field property of the params.

**Comment by jeffreyschultz** [comment]
There might need to be a check that ensures that referenced entity properties actually exist. I set the field parameter to `document_id`, which is the column name, but the entity's property is `documentId`. It almost generated a working query, if it weren't for the need to quote the table and column in the query.

Might be a good todo.
