### ISSUE TITLE
Cannot read property 'connection' of undefined 

### ISSUE THREAD

**Issue by sale7i** [nestjsx/crud#529]
I'm trying to setup nextjscrud with in [awesome-nest-boilerplate](https://github.com/NarHakobyan/awesome-nest-boilerplate) but I'm getting this weird error below and I noticed that this file isn't found on  **node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts**
everything is copied from docs , except I had my changes on my entity
`[Nest] 133764   - 06/04/2020, 10:08:36 AM   [ExceptionHandler] Cannot read property 'connection' of undefined +36ms`
`TypeError: Cannot read property 'connection' of undefined
    at new TypeOrmCrudService (node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:69:38)`
`    at new CallService (src/modules/device/call.service.ts:9:9)
    at Injector.instantiateClass (node_modules/@nestjs/core/injector/injector.js:289:19)
    at callback (node_modules/@nestjs/core/injector/injector.js:76:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Injector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:117:24)
    at Injector.loadInstance (node_modules/@nestjs/core/injector/injector.js:80:9)
    at Injector.loadProvider (node_modules/@nestjs/core/injector/injector.js:37:9)
    at async Promise.all (index 9)
    at InstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:42:9)
`

**Comment by zMotivat0r** [comment]
Make sure you import TypeOrm module properly.
Also please make sure that your crud service is injected as a public property.
https://github.com/nestjsx/crud/wiki/Controllers#install
