### ISSUE TITLE
Adding a filter into the query result to querying an undefined column

### ISSUE THREAD

**Issue by fstn** [nestjsx/crud#580]
I try to add an extra filter inside my interceptor like this:

```
  @Injectable()
  export class AuthInterceptor<T, R> implements NestInterceptor<T, R> {
    // eslint-disable-next-line class-methods-use-this
    public intercept(context: ExecutionContext, next: CallHandler): Observable<R> {
      const req = context.switchToHttp().getRequest()
  
      if (req.method === 'POST') {
        // Works for createOneBase route.
        req.body.user = {id:req.user.id};
      } else {
        // Works for getManyBase, getOneBase, updateOneBase, replaceOneBase, deleteOneBase routes.
        req.query.filter = `userid||eq||1`;
      }
  
      return next.handle();
    }
  }
```

But the result in my controller is:

```
JSON.stringify(req.parsed,null,2)
'{
  "fields": [],
  "paramsFilter": [],
  "search": {
    "$and": [
      null,
      {},
      {
        "userid": {
          "eq": 1
        }
      }
    ]
  },
  "filter": [
    {
      "field": "userid",
      "operator": "eq",
      "value": 1
    }
  ],
  "or": [],
  "join": [],
  "sort": []
}'
```

As you can see there is an extra search null that make the orm query an undefined column:

```
error: Error: SQLITE_ERROR: no such column: Company.undefined
--> in Database#all('SELECT "Company"."id" AS "Company_id", "Company"."name" AS "Company_name", "Company"."userId" FROM "company" "Company" WHERE ("Company"."undefined" = ?)', [ 1 ], [Function: handler])
    at SqliteQueryRunner.<anonymous> (/Users/stephenzambaux/nest-js-crud/api/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:64:48)
    at step (/Users/stephenzambaux/nest-js-crud/api/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/stephenzambaux/nest-js-crud/api/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/stephenzambaux/nest-js-crud/api/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
```

I can workaround it by doing  `req.query.filter = `Company.userid||eq||1`;` instead of  `req.query.filter = `userid||eq||1`;` but I don't want to do that.

This is my entity:
```
@Entity()
export class Company {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;

  @ManyToOne(()=>User,{nullable:false})
  user: User
}
```

**Comment by zMotivat0r** [comment]
Please see this issue https://github.com/nestjsx/crud/issues/532#issuecomment-640425646
