### ISSUE TITLE
Malformed SQL generated from @CrudAuth filter for foreign key on 4.6.1+

### ISSUE THREAD

**Issue by pcaisse** [nestjsx/crud#684]
I have a project entity like so (notice the `user_id` column):
```ts
@Entity()
export class Project implements IProject {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column({ type: "character varying" })
  name: string;

  @ManyToOne(() => RegionConfig, { nullable: false })
  @JoinColumn({ name: "region_config_id" })
  regionConfig: RegionConfig;

  @ManyToOne(() => Chamber, { nullable: true })
  @JoinColumn({ name: "chamber_id" })
  chamber?: Chamber;

  @ManyToOne(() => ProjectTemplate, { nullable: true, onDelete: "SET NULL" })
  @JoinColumn({ name: "project_template_id" })
  projectTemplate?: ProjectTemplate;

  @Column({ name: "number_of_districts", type: "integer" })
  numberOfDistricts: number;

  @Column({
    type: "jsonb",
    name: "districts_definition",
    nullable: true
  })
  districtsDefinition: DistrictsDefinition;

  @Column({
    type: "jsonb",
    name: "districts",
    nullable: true
  })
  districts: DistrictsGeoJSON;

  @ManyToOne(() => User, { nullable: false, eager: true })
  @JoinColumn({ name: "user_id" })
  user: User;

  @Column({ type: "timestamp with time zone", name: "created_dt", default: () => "NOW()" })
  createdDt: Date;

  @UpdateDateColumn({
    type: "timestamp with time zone",
    name: "updated_dt",
    default: () => "NOW()"
  })
  updatedDt: Date;

  @Column({ type: "boolean", default: false })
  advancedEditingEnabled: boolean;

  @Column({
    type: "boolean",
    name: "locked_districts",
    array: true,
    default: () => "'{}'"
  })
  lockedDistricts: readonly boolean[];

  @Column({ type: "enum", enum: ProjectVisibility, default: ProjectVisibility.Private })
  visibility: ProjectVisibility;

  @Column({ type: "boolean", default: false })
  archived: boolean;

  @Column({ type: "boolean", default: false })
  isFeatured: boolean;

  // Strips out data that we don't want to have available in the read-only view in the UI
  getReadOnlyView(): Project {
    return { ...this, lockedDistricts: new Array(this.numberOfDistricts).fill(false) };
  }
}
```

and a projects controller which filters on `user_id`:
```ts
@Crud({
  model: {
    type: Project
  },
  params: {
    id: {
      type: "string",
      primary: true,
      field: "id"
    }
  },
  query: {
    join: {
      projectTemplate: {
        exclude: ["districtsDefinition"],
        eager: true
      },
      "projectTemplate.organization": {
        eager: true
      },
      "projectTemplate.organization.admin": {
        alias: "org_admin",
        eager: false
      },
      "projectTemplate.regionConfig": {
        alias: "template_region_config",
        eager: true
      },
      regionConfig: {
        eager: true
      },
      user: {
        allow: ["id", "name"] as PublicUserProperties[],
        alias: "project_user",
        required: true,
        eager: true
      }
    }
  },
  routes: {
    only: ["createOneBase", "getManyBase", "getOneBase", "updateOneBase"]
  },
  dto: {
    update: UpdateProjectDto
  }
})
@CrudAuth({
  filter: (req: any) => {
    const user = req.user as User;
    return {
      user_id: user ? user.id : undefined
    };
  },
  persist: (req: any) => {
    const user = req.user as User;
    return {
      userId: user ? user.id : undefined
    };
  }
})
@Controller("api/projects")
// @ts-ignore
export class ProjectsController implements CrudController<Project> {
  ...
}
```

Prior to version 4.6.1, filtering projects by user worked fine. After upgrading to 4.6.1, there is this error:
```
server_1    | error: error: column Project.undefined does not exist
server_1    |     at Connection.parseE (/home/node/app/server/node_modules/pg/lib/connection.js:604:13)
server_1    |     at Connection.parseMessage (/home/node/app/server/node_modules/pg/lib/connection.js:403:19)
server_1    |     at Socket.<anonymous> (/home/node/app/server/node_modules/pg/lib/connection.js:123:22)
server_1    |     at Socket.emit (events.js:314:20)
server_1    |     at Socket.EventEmitter.emit (domain.js:483:12)
server_1    |     at addChunk (_stream_readable.js:297:12)
server_1    |     at readableAddChunk (_stream_readable.js:272:9)
server_1    |     at Socket.Readable.push (_stream_readable.js:213:10)
server_1    |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
server_1    |   length: 117,
server_1    |   severity: 'ERROR',
server_1    |   code: '42703',
server_1    |   detail: undefined,
server_1    |   hint: undefined,
server_1    |   position: '3195',
server_1    |   internalPosition: undefined,
server_1    |   internalQuery: undefined,
server_1    |   where: undefined,
server_1    |   schema: undefined,
server_1    |   table: undefined,
server_1    |   column: undefined,
server_1    |   dataType: undefined,
server_1    |   constraint: undefined,
server_1    |   file: 'parse_relation.c',
server_1    |   line: '3359',
server_1    |   routine: 'errorMissingColumn'
server_1    | }
server_1    | [Nest] 39   - 03/19/2021, 3:21:21 PM   [ExceptionsHandler] column Project.undefined does not exist +3879ms
server_1    | QueryFailedError: column Project.undefined does not exist
server_1    |     at new QueryFailedError (/home/node/app/server/node_modules/typeorm/error/QueryFailedError.js:11:28)
server_1    |     at PostgresQueryRunner.<anonymous> (/home/node/app/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)
server_1    |     at step (/home/node/app/server/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
server_1    |     at Object.throw (/home/node/app/server/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
server_1    |     at rejected (/home/node/app/server/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
server_1    |     at runMicrotasks (<anonymous>)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
This is the SQL generated for the failed query (notice the `WHERE` clause at the end):
```
server_1    | query failed: SELECT "Project"."id" AS "Project_id", "Project"."name" AS "Project_name", "Project"."number_of_districts" AS "Project_number_of_districts", "Project"."districts_definition" AS "Project_districts_definition", "Project"."districts" AS "Project_districts", "Project"."created_dt" AS "Project_created_dt", "Project"."updated_dt" AS "Project_updated_dt", "Project"."advancedEditingEnabled" AS "Project_advancedEditingEnabled", "Project"."locked_districts" AS "Project_locked_districts", "Project"."visibility" AS "Project_visibility", "Project"."archived" AS "Project_archived", "Project"."isFeatured" AS "Project_isFeatured", "projectTemplate"."id" AS "projectTemplate_id", "projectTemplate"."name" AS "projectTemplate_name", "projectTemplate"."number_of_districts" AS "projectTemplate_number_of_districts", "projectTemplate"."description" AS "projectTemplate_description", "projectTemplate"."details" AS "projectTemplate_details", "projectTemplate"."organization_id" AS "projectTemplate_organization_id", "projectTemplate"."region_config_id" AS "projectTemplate_region_config_id", "projectTemplate"."chamber_id" AS "projectTemplate_chamber_id", "organization"."id" AS "organization_id", "organization"."slug" AS "organization_slug", "organization"."name" AS "organization_name", "organization"."description" AS "organization_description", "organization"."logoUrl" AS "organization_logoUrl", "organization"."linkUrl" AS "organization_linkUrl", "organization"."municipality" AS "organization_municipality", "organization"."region" AS "organization_region", "organization"."user_id" AS "organization_user_id", "template_region_config"."id" AS "template_region_config_id", "template_region_config"."name" AS "template_region_config_name", "template_region_config"."country_code" AS "template_region_config_country_code", "template_region_config"."region_code" AS "template_region_config_region_code", "template_region_config"."s3_uri" AS "template_region_config_s3_uri", "template_region_config"."version" AS "template_region_config_version", "template_region_config"."hidden" AS "template_region_config_hidden", "regionConfig"."id" AS "regionConfig_id", "regionConfig"."name" AS "regionConfig_name", "regionConfig"."country_code" AS "regionConfig_country_code", "regionConfig"."region_code" AS "regionConfig_region_code", "regionConfig"."s3_uri" AS "regionConfig_s3_uri", "regionConfig"."version" AS "regionConfig_version", "regionConfig"."hidden" AS "regionConfig_hidden", "project_user"."id" AS "project_user_id", "project_user"."name" AS "project_user_name", "Project"."region_config_id", "Project"."chamber_id", "Project"."project_template_id", "Project"."user_id" FROM "project" "Project" LEFT JOIN "project_template" "projectTemplate" ON "projectTemplate"."id"="Project"."project_template_id"  LEFT JOIN "organization" "organization" ON "organization"."id"="projectTemplate"."organization_id"  LEFT JOIN "region_config" "template_region_config" ON "template_region_config"."id"="projectTemplate"."region_config_id"  LEFT JOIN "region_config" "regionConfig" ON "regionConfig"."id"="Project"."region_config_id"  INNER JOIN "user" "project_user" ON "project_user"."id"="Project"."user_id" WHERE ("Project"."undefined" = $1) ORDER BY "Project"."updated_dt" DESC -- PARAMETERS: ["07f9966f-facf-42ce-a4ee-48320007f1cc"]
```
I believe the regression is here (`field` must be missing from `this.entityColumnsHash`): https://github.com/nestjsx/crud/compare/v4.6.0...v4.6.1#diff-b2df54e8bb3cd81b3f026eb38b70eb58c15e84d1b463f42cc788e64b8dc7e860R842-R843

**Comment by futbotism** [comment]
+1 getting this issue with `4.6.2` for the following code. downgrading to `4.5.0` fixed it

```
@CrudAuth({
  filter: (req: any) => {
    return {
      userId: req.user.id,
    };
  },
  persist: (req: any) => ({
    userId: req.user.id,
    user: req.user,
  }),
})

**Comment by beneccli** [comment]
Downgrading to `4.6.0` fixes this issue also if anyone needs features coming from this version. Versions above introduce this bug.
