### ISSUE TITLE
Support for @ViewEntity

### ISSUE THREAD

**Issue by bertyhell** [nestjsx/crud#686]
How hard would it be to add support for @ViewEntity

Only the get routes could be supported since it's a view
```
getManyBase, getOneBase
```

Example entity:
```

@ViewEntity('reports')
export class ReportEntity {
  @ApiProperty()
  @ViewColumn()
  date: Date;

  @ApiProperty()
  @ViewColumn()
  templateName: string;

  @ApiProperty()
  @ViewColumn()
  templateId: string;

  @ApiProperty()
  @ViewColumn()
  departmentName: string;

  @ApiProperty()
  @ViewColumn()
  departmentId: string;
}
```

Current behavior:
Errors at the top of the swagger docs:
![image](https://user-images.githubusercontent.com/1710840/112443182-f016f780-8d4c-11eb-9974-7b7fb1b93a0e.png)

Error when trying out the getMany endpoint:
```
[2021-03-25 08:28:55] WARN: [Request]: GET /api/reports?fields=date,templateName&limit=30
    environment: "LOCAL"
    traceId: "dd5c3c5a-74cd-4e59-abfb-81f3174b1190"
    context: "Request"
    status: 500
    code: "Unknown error"
    description: "No description"
    duration: "114ms"
    params: {}
    query: {"fields":"date,templateName","limit":"30"}
    body: {}
    host: "localhost"
[2021-03-25 08:28:55] ERROR: [ExceptionsHandler]: column ReportEntity.date does not exist
    environment: "LOCAL"
    traceId: "dd5c3c5a-74cd-4e59-abfb-81f3174b1190"
    context: "ExceptionsHandler"
    error: "QueryFailedError: column ReportEntity.date does not exist
at new QueryFailedError (C:\\...\\src\\error\\QueryFailedError.ts:9:9)  
at PostgresQueryRunner.<anonymous> (C:\\...\\src\\driver\\postgres\\PostgresQueryRunner.ts:228:19)   
at step (C:\\...\\node_modules\\typeorm\\node_modules\\tslib\\tslib.js:141:27)
at Object.throw (C:\\...\\node_modules\\typeorm\\node_modules\\tslib\\tslib.js:122:57)
at rejected (C:\\...\\node_modules\\typeorm\\node_modules\\tslib\\tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Any pointers on how i would make a PR for this. What files i would need to modify/create?

**Comment by bertyhell** [comment]
nvm, it had more todo with the filter than with the ViewEntity.

This was my solution:
```typescript
@Crud({
  model: {
    type: ReportEntity,
  },
  routes: {
    only: ['getManyBase'],
  },
  query: {
    filter: {
      '"ReportEntity"."isDeleted"': false,
    },
  },
})
@Controller('reports')
export class ReportsController implements CrudController<ReportEntity> {
  constructor(public readonly service: ReportsService) {}
}
```
