### ISSUE TITLE
One-To-Many / Many-To-One cannot be query/joined

### ISSUE THREAD

**Issue by ghostlexly** [nestjsx/crud#779]
Hello, i'm new on nestjs,
i have an issue with the join of these two entities, can't find why...
any help ?..

Geozone.ts
`ts
@Entity()
export class Geozone extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @IsDefined()
  @Validate(RelationExists, [{ targetEntity: "housekeeper", targetField: "id" }])
  @ApiProperty({ type: "number" })
  @ManyToOne(() => Housekeeper, (hs) => hs.geozones)
  @JoinColumn()
  owner: Housekeeper;

  @ApiProperty()
  @Column()
  postalCode: string;
}
`

Housekeeper.ts
`ts
@Entity()
export class Housekeeper extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty()
  @IsEmail()
  @Column({ unique: true })
  email: string;

  @OneToMany(() => Geozone, (geozone) => geozone.owner)
  geozones: Geozone[];
}
`

Here is the error:

`
backend_1       | [Nest] 2197  - 04/16/2022, 6:27:43 PM     LOG [NestApplication] Nest application successfully started +1ms
backend_1       | [Nest] 2197  - 04/16/2022, 6:28:24 PM   ERROR [ExceptionsHandler] Duplicate column name 'Housekeeper_id'
backend_1       | QueryFailedError: Duplicate column name 'Housekeeper_id'
backend_1       |     at Query.onResult (/usr/src/app/src/driver/mysql/MysqlQueryRunner.ts:222:33)
backend_1       |     at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:36:14)
backend_1       |     at PoolConnection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
backend_1       |     at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
backend_1       |     at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
backend_1       |     at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
backend_1       |     at Socket.emit (node:events:390:28)
backend_1       |     at addChunk (node:internal/streams/readable:315:12)
backend_1       |     at readableAddChunk (node:internal/streams/readable:289:9)
backend_1       |     at Socket.Readable.push (node:internal/streams/readable:228:10)
`

**Comment by ghostlexly** [comment]
i found that this issue appears only when "limit" is set in query.

**Comment by ludovit-ubrezi** [comment]
> 

Did you found out how it can be used with limit? Because it is basic paging functionality ... trying to tag team member @fwoelffel

**Comment by zetti-caletti** [comment]
Have same problem. It appears if limit is set. Why doesn't this get fixed? There are so many open Issues here.

**Comment by Kannan18Msc** [comment]
please try as it is entities field name  @ghostlexly 
![Screenshot 2024-03-06 at 2 34 00 PM](https://github.com/nestjsx/crud/assets/127466663/6bfd4569-76f6-426d-b76d-681ce9fd0fcf)
![Screenshot 2024-03-06 at 2 35 49 PM](https://github.com/nestjsx/crud/assets/127466663/93211273-cefe-4260-8809-0afa03bdc48c)
